# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [3]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

In [4]:
import numpy as np

### Part 1: Data Exploration ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

In [6]:
# Part 1

print(df.shape)
print(df.columns)

(891, 12)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
# Part 2

df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
# Part 3

df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### Part 2: Indexing and Selection ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

In [10]:
%%time

# 1
df[['Name']]

CPU times: total: 0 ns
Wall time: 999 μs

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                        Graham, Miss Margaret Edith
888            Johnston, Miss Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

In [11]:
# 2
df[['Name', 'Sex', 'Age', 'Fare']]

                                                  Name     Sex   Age     Fare
0                              Braund, Mr. Owen Harris    male  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0  71.2833
2                                Heikkinen, Miss Laina  female  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0  53.1000
4                             Allen, Mr. William Henry    male  35.0   8.0500
..                                                 ...     ...   ...      ...
886                              Montvila, Rev. Juozas    male  27.0  13.0000
887                        Graham, Miss Margaret Edith  female  19.0  30.0000
888            Johnston, Miss Catherine Helen "Carrie"  female   NaN  23.4500
889                              Behr, Mr. Karl Howell    male  26.0  30.0000
890                                Dooley, Mr. Patrick    male  32.0   7.7500

[891 rows x 4 columns]

In [12]:
# 3
df.iloc[37]

PassengerId                          38
Survived                              0
Pclass                                3
Name           Cann, Mr. Ernest Charles
Sex                                male
Age                                21.0
SibSp                                 0
Parch                                 0
Ticket                       A./5. 2152
Fare                               8.05
Cabin                               NaN
Embarked                              S
Name: 37, dtype: object

In [13]:
# 4
df.iloc[100:105, 2:6]

     Pclass                              Name     Sex   Age
100       3            Petranec, Miss Matilda  female  28.0
101       3  Petroff, Mr. Pastcho ("Pentcho")    male   NaN
102       1         White, Mr. Richard Frasar    male  21.0
103       3        Johansson, Mr. Gustaf Joel    male  33.0
104       3    Gustafsson, Mr. Anders Vilhelm    male  37.0

### Part 3: Filtering ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

In [15]:
%%time

# 1
tdf = df[df['Age'] > 60]
tdf.head()

CPU times: total: 0 ns
Wall time: 999 μs

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S

In [16]:
# 2
tdf1 = df[(df['Fare']>100) & (df['Pclass'] == 1)]
tdf1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
88,89,1,1,"Fortune, Miss Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.0,0,1,PC 17558,247.5208,B58 B60,C
195,196,1,1,"Lurette, Miss Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

In [17]:
# 3
missing_age = df[df['Age'].isnull()]
print(f"{len(missing_age)} with no age")
missing_age[['Name', 'Age', 'Pclass', 'Sex']]

177 with no age

                                        Name  Age  Pclass     Sex
5                           Moran, Mr. James  NaN       3    male
17              Williams, Mr. Charles Eugene  NaN       2    male
19                   Masselmani, Mrs. Fatima  NaN       3  female
26                   Emir, Mr. Farred Chehab  NaN       3    male
28              O'Dwyer, Miss Ellen "Nellie"  NaN       3  female
..                                       ...  ...     ...     ...
859                         Razi, Mr. Raihed  NaN       3    male
863         Sage, Miss Dorothy Edith "Dolly"  NaN       3  female
868              van Melkebeke, Mr. Philemon  NaN       3    male
878                       Laleff, Mr. Kristo  NaN       3    male
888  Johnston, Miss Catherine Helen "Carrie"  NaN       3  female

[177 rows x 4 columns]

### Part 4: Reindexing and Dropping ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

In [19]:
# 1

df_reversed = df.reindex(index=df.index[::-1])
df_reversed.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S

In [20]:
# 2

df_dropped_col = df.drop('Fare', axis=1)
df_dropped_col.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,NaN,S

In [21]:
# 3

df_dropped_nullAge = df.dropna(subset=['Age']) #dropna for null values
df_dropped_nullAge

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Part 5: Arithmetic and Data Alignment ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

In [23]:
%%time

# 1

USD_TO_EUR = 0.86
df['Fare_EUR'] = df['Fare'] * USD_TO_EUR
df.head()

CPU times: total: 0 ns
Wall time: 998 μs

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_EUR
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000

In [24]:
# 2

df['AgeCenter'] = df['Age'] - df['Age'].mean()
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_EUR,AgeCenter
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000,-7.699118
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638,8.300882
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500,-3.699118
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000,5.300882
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000,5.300882

In [25]:
# 3

custom_array = np.random.randint(1, 10, size=len(df))  # one value for each row in the df

df[['SibSp', 'Parch']].subtract(custom_array, axis=0).head()

   SibSp  Parch
0     -5     -6
1     -5     -6
2     -7     -7
3      0     -1
4     -8     -8

### Part 6: Applying Functions ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

In [27]:
# 1

df['NameLength'] = df['Name'].apply(lambda x: len(x))
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_EUR,AgeCenter,NameLength
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.235000,-7.699118,23
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,61.303638,8.300882,51
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,6.815500,-3.699118,21
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,45.666000,5.300882,44
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,6.923000,5.300882,24

In [28]:
# 2

df['FareMinusAge'] = df['Fare'] - df['Age']

df[['Fare', 'Age', 'FareMinusAge']].head()

      Fare   Age  FareMinusAge
0   7.2500  22.0      -14.7500
1  71.2833  38.0       33.2833
2   7.9250  26.0      -18.0750
3  53.1000  35.0       18.1000
4   8.0500  35.0      -26.9500

In [29]:
# 3

numeric_cols = df.select_dtypes(include='number').columns # selects certain type of data for each column
df[numeric_cols] = df[numeric_cols].round(1) #rounds to one decimal place

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_EUR,AgeCenter,NameLength,FareMinusAge
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2,NaN,S,6.2,-7.7,23,-14.8
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.3,C85,C,61.3,8.3,51,33.3
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9,NaN,S,6.8,-3.7,21,-18.1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S,45.7,5.3,44,18.1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0,NaN,S,6.9,5.3,24,-27.0

### Part 7: Mapping and Transformation ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

In [31]:
# 1

df['SexCode'] = df['Sex'].map({'male': 0, 'female': 1})
df[['Sex', 'SexCode']].head()

      Sex  SexCode
0    male        0
1  female        1
2  female        1
3  female        1
4    male        0

In [32]:
# 2

def age_func(x):
    if pd.isnull(x):
        return None
    elif x <= 12:
        return 'Child'
    elif x <= 19:
        return 'Teenager'
    elif x <= 60:
        return 'Adult'
    else:
        return 'Senior'

df['AgeGroup'] = df['Age'].map(age_func)
df[['Age', 'AgeGroup']].head(10)

    Age  AgeGroup
0  22.0     Adult
1  38.0     Adult
2  26.0     Adult
3  35.0     Adult
4  35.0     Adult
5   NaN      None
6  54.0     Adult
7   2.0     Child
8  27.0     Adult
9  14.0  Teenager

### Part 8: Python ###

1. Select the names column. (2.3)

2. Show only the rows where the age is above 60. (3.1)

3. Create a new column that converts fares from USD to Euros. (5.1)

In [34]:
# Asked Claude "how to open csv file into a list without pandas" (but i chose the implementation that turns it into a dictionary bc it's cleaner :100: and probably easier

import urllib.request
import csv

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

with urllib.request.urlopen(url) as response:
    lines = [l.decode('utf-8') for l in response.readlines()]
    reader = csv.DictReader(lines)
    data = list(reader)

In [35]:
%%time

# 1

names = [row['Name'] for row in data] # names 
print(names[:5]) # print up to 5

['Braund, Mr. Owen Harris', 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Heikkinen, Miss. Laina', 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'Allen, Mr. William Henry']
CPU times: total: 0 ns
Wall time: 998 μs

In [36]:
%%time

# 2

# creating a list of elderly
elderly = [row for row in data if row['Age'] != '' and float(row['Age']) > 60]

# display
for row in elderly[:5]:
    print(row['Name'], '|', row['Age'])

Wheadon, Mr. Edward H | 66
Ostby, Mr. Engelhart Cornelius | 65
Goldschmidt, Mr. George B | 71
Connors, Mr. Patrick | 70.5
Van der hoef, Mr. Wyckoff | 61
CPU times: total: 0 ns
Wall time: 0 ns

In [37]:
%%time

# 3

USD_TO_EUR = 0.86

for row in data:
    row['Fare_EUR'] = float(row['Fare']) * USD_TO_EUR

# check result
for row in data[:5]:
    print(row['Fare'], 'in Euros:', row['Fare_EUR'])

7.25 in Euros: 6.235
71.2833 in Euros: 61.303638
7.925 in Euros: 6.8155
53.1 in Euros: 45.666000000000004
8.05 in Euros: 6.923000000000001
CPU times: total: 15.6 ms
Wall time: 2.01 ms

### Observations

I'm going to be real with you I can barely see a difference in execution time LOL

I'm assuming pandas would do it faster? I'm on jupyter lab and I read I should use %%time but I lowkey don't understand what these mean...

(https://stackoverflow.com/questions/43307653/measure-runtime-of-a-jupyter-notebook-code-cell)